#!/bin/sh
# The following lines instruct Slurm to allocate one GPU.
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=60G
#SBATCH -o log.nu.afp
#SBATCH -e err.nu.afp
source ${HOME}/.bashrc

#source activate py27
export DATA=/zfs/ilps-plex1/slurm/datastore/pdakwal1/py-op/arabic/segments/afp/data/
export MODEL=/zfs/ilps-plex1/slurm/datastore/pdakwal1/py-op/arabic/segments/afp/non-update-model/
python -u train.py -data $DATA/afp-data -save_model $MODEL/continue.afp-model -src_word_vec_size 1000 -tgt_word_vec_size 1000 -rnn_size 1000 -epochs 13 -train_from1  /zfs/ilps-plex1/slurm/datastore/pdakwal1/py-op/arabic/segments/afp/model/afp-arabic-model_acc_33.73_ppl_45.54_e2.pt -train_from2 /zfs/ilps-plex1/slurm/datastore/pdakwal1/py-op/arabic/segments/afp/0.2model/0.05afp-arabic-model_acc_36.05_ppl_40.39_e2.pt -gpuid 0
